// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import Image from './Image';
import ImageCards from './ImageCards';
import ProjectList from './ProjectList';
import Quote from './Quote';
import RelatedTechnologies from './RelatedTechnologies';
import Text from './Text';
import TextWithImage from './TextWithImage';

export {
	Hero,
	Image,
	ImageCards,
	ProjectList,
	Quote,
	RelatedTechnologies,
	Text,
	TextWithImage,
};

export const components = {
	hero: Hero,
	image: Image,
	image_cards: ImageCards,
	project: ProjectList,
	quote: Quote,
	related_technologies: RelatedTechnologies,
	text: Text,
	text_with_image: TextWithImage,
};
